services:
  db:
    image: postgres:17
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'www'
      POSTGRES_USER: 'apache'
      POSTGRES_PASSWORD: 'passwordp'
volumes:
  db-store: